//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,_9FHMwaMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Desenvolvimento_4F3255D3_b9b98bb1_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,_3n6kQaMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Ideação_C2E52397_2d6c5975_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,_6EcREaMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Prototipação_BCEF8B31_2776c10f_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,_-0m0caMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Testes_BE79BBBB_2900f199_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,_8LZ9kaMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Análise_157D3260_8004683e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,__wuecaMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Deploy_5459357D_bee06b5b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hm91kaMeEeuaPL768T4xXQ,_yrOn0aMeEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/capabilitypatterns/resources/Análise_6ED8EFA0_d960257e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_ZIWlUKMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Prototipação_8DCC0723_b368562a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_XLPYYaMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Ideação_E59F10E_33f64015_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_c1wEIaMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Desenvolvimento_7130F4BD_96cd43c4_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_UerrgaMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Imersão_4ED51CF3_74716bfa_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_bmT1gaMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Análise_2B2D51EB_50c9a0f2_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_e2a7YaMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Deploy_ACB9BCB4_d2560bbb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQ,_d_UUQaMwEeuaPL768T4xXQActivityDetail"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Testes_76E980F4_9c85cffb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hcqsQaMtEeuaPL768T4xXQActivity"]="./../../Juciane_Design Thinking Adapter/deliveryprocesses/resources/Fluxo_Design_Thinking_Adapter_257CE9B3_257ce9b3_Activity.jpeg"
contentPage.processPage.elementUrls["_fUwhY6MpEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_RUzQ06MtEeuaPL768T4xXQ"] = ["profissional de devops","Juciane_Design Thinking Adapter/roles/profissional_de_devops_1D4ED559.html"];
contentPage.processPage.elementUrls["_CDwL0KMxEeuaPL768T4xXQ"] = ["aplicação preparada para testes","Juciane_Design Thinking Adapter/workproducts/aplicacao_preparada_para_testes_8DC6236D.html"];
contentPage.processPage.elementUrls["_yaQHZ6MwEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_2Lb6A6MwEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_0xedcaMwEeuaPL768T4xXQ"] = ["designer","Juciane_Design Thinking Adapter/roles/designer_78C0B9A6.html"];
contentPage.processPage.elementUrls["_JHO1oaMxEeuaPL768T4xXQ"] = ["aplicação executando em ambiente de produção","Juciane_Design Thinking Adapter/workproducts/aplicacao_executando_em_ambiente_de_producao_4698C099.html"];
contentPage.processPage.elementUrls["_hcqsQaMtEeuaPL768T4xXQ"] = ["Fluxo_Design_Thinking_Adapter","Juciane_Design Thinking Adapter/deliveryprocesses/Fluxo_Design_Thinking_Adapter_257CE9B3.html"];
contentPage.processPage.elementUrls["_dkQ0JaMpEeuaPL768T4xXQ"] = ["protótipo da aplicação","Juciane_Design Thinking Adapter/workproducts/prototipo_da_aplicacao_3F3EB527.html"];
contentPage.processPage.elementUrls["_POS3UaMtEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_Poui16MoEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_M7gN86MwEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_l9FZ4aMhEeuaPL768T4xXQ"] = ["relatório sobre o cliente","Juciane_Design Thinking Adapter/workproducts/relatorio_sobre_o_cliente_C02A708B.html"];
contentPage.processPage.elementUrls["_0xedcKMwEeuaPL768T4xXQ"] = ["desenvolver um protótipo da aplicação","Juciane_Design Thinking Adapter/tasks/desenvolver_um_prototipo_da_aplicacao_A0BA7727.html"];
contentPage.processPage.elementUrls["_imMWkKMhEeuaPL768T4xXQ"] = ["Analisar o problema","Juciane_Design Thinking Adapter/tasks/analisar_o_problema_20968CD5.html"];
contentPage.processPage.elementUrls["_fUwhYaMpEeuaPL768T4xXQ"] = ["Cliente","Juciane_Design Thinking Adapter/roles/cliente_B8D3AF02.html"];
contentPage.processPage.elementUrls["_AWRWU6MxEeuaPL768T4xXQ"] = ["profissional de devops","Juciane_Design Thinking Adapter/roles/profissional_de_devops_1D4ED559.html"];
contentPage.processPage.elementUrls["_4TucNKMwEeuaPL768T4xXQ"] = ["definição das tarefas de desenvolvimento","Juciane_Design Thinking Adapter/workproducts/definicao_das_tarefas_de_desenvolvimento_71469337.html"];
contentPage.processPage.elementUrls["_tpGslaMwEeuaPL768T4xXQ"] = ["atendimento ao cliente","Juciane_Design Thinking Adapter/roles/atendimento_ao_cliente_E50741EE.html"];
contentPage.processPage.elementUrls["_AWRWUaMxEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_8LZ9kaMeEeuaPL768T4xXQ"] = ["Análise","Juciane_Design Thinking Adapter/capabilitypatterns/Análise_157D3260.html"];
contentPage.processPage.elementUrls["_SvBzIKMtEeuaPL768T4xXQ"] = ["Preparar aplicação para testes","Juciane_Design Thinking Adapter/tasks/preparar_aplicacao_para_testes_A8173545.html"];
contentPage.processPage.elementUrls["_-SF4E6MwEeuaPL768T4xXQ"] = ["definição das tarefas de desenvolvimento","Juciane_Design Thinking Adapter/workproducts/definicao_das_tarefas_de_desenvolvimento_71469337.html"];
contentPage.processPage.elementUrls["_2Lb6AKMwEeuaPL768T4xXQ"] = ["Apresentação do protótipo para o cliente","Juciane_Design Thinking Adapter/tasks/apresentacao_do_prototipo_para_o_cliente_771A0F28.html"];
contentPage.processPage.elementUrls["_tpGsk6MwEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_wIECUKMwEeuaPL768T4xXQ"] = ["Analisar os potenciais competidores","Juciane_Design Thinking Adapter/tasks/analisar_os_potenciais_competidores_462BB05A.html"];
contentPage.processPage.elementUrls["_fnQUsaMrEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_hm91kaMeEeuaPL768T4xXQ"] = ["Fases_Design_Thinking_Adapter","Juciane_Design Thinking Adapter/capabilitypatterns/Fases_Design_Thinking_Adapter_A518258A.html"];
contentPage.processPage.elementUrls["_h8CawaMrEeuaPL768T4xXQ"] = ["atribuição das tarefas de desenvolvimento","Juciane_Design Thinking Adapter/workproducts/atribuicao_das_tarefas_de_desenvolvimento_A9A7932A.html"];
contentPage.processPage.elementUrls["_OtgXEKMwEeuaPL768T4xXQ"] = ["colocar aplicação em produção","Juciane_Design Thinking Adapter/tasks/colocar_aplicacao_em_producao_802DF2D1.html"];
contentPage.processPage.elementUrls["_UerrgaMwEeuaPL768T4xXQ"] = ["Imersão","Juciane_Design Thinking Adapter/deliveryprocesses/Imersão_4ED51CF3.html"];
contentPage.processPage.elementUrls["_8FbzQaMwEeuaPL768T4xXQ"] = ["atribuição das tarefas de desenvolvimento","Juciane_Design Thinking Adapter/workproducts/atribuicao_das_tarefas_de_desenvolvimento_A9A7932A.html"];
contentPage.processPage.elementUrls["_3n6kQaMeEeuaPL768T4xXQ"] = ["Ideação","Juciane_Design Thinking Adapter/capabilitypatterns/Ideação_C2E52397.html"];
contentPage.processPage.elementUrls["_M7gN8KMwEeuaPL768T4xXQ"] = ["Configurar o ambiente de produção","Juciane_Design Thinking Adapter/tasks/configurar_o_ambiente_de_producao_8F531151.html"];
contentPage.processPage.elementUrls["_yaQHZaMwEeuaPL768T4xXQ"] = ["relatório da análise do problema","Juciane_Design Thinking Adapter/workproducts/relatorio_da_analise_do_problema_5A197C2D.html"];
contentPage.processPage.elementUrls["_u1x7EKMwEeuaPL768T4xXQ"] = ["Coletar informações sobre o cliente","Juciane_Design Thinking Adapter/tasks/coletar_informacoes_sobre_o_cliente_D5180351.html"];
contentPage.processPage.elementUrls["_Poui1aMoEeuaPL768T4xXQ"] = ["relatório da análise do problema","Juciane_Design Thinking Adapter/workproducts/relatorio_da_analise_do_problema_5A197C2D.html"];
contentPage.processPage.elementUrls["_-SF4FaMwEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_GaRgJ6MxEeuaPL768T4xXQ"] = ["ambiente de produção configurado","Juciane_Design Thinking Adapter/workproducts/ambiente_de_producao_configurado_273D6861.html"];
contentPage.processPage.elementUrls["_-SF4EaMwEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_4TlSQKMwEeuaPL768T4xXQ"] = ["Definir as tarefas de desenvolvimento","Juciane_Design Thinking Adapter/tasks/definir_as_tarefas_de_desenvolvimento_7AA89A34.html"];
contentPage.processPage.elementUrls["_0xedc6MwEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_imRPFqMhEeuaPL768T4xXQ"] = ["Descrição do cliente sobre o problema","Juciane_Design Thinking Adapter/workproducts/descricao_do_cliente_sobre_o_problema_B785C4CF.html"];
contentPage.processPage.elementUrls["_AWRWVaMxEeuaPL768T4xXQ"] = ["aplicação funcional","Juciane_Design Thinking Adapter/workproducts/aplicacao_funcional_F915469D.html"];
contentPage.processPage.elementUrls["_RUzQ1aMtEeuaPL768T4xXQ"] = ["aplicação funcional","Juciane_Design Thinking Adapter/workproducts/aplicacao_funcional_F915469D.html"];
contentPage.processPage.elementUrls["_-SF4EKMwEeuaPL768T4xXQ"] = ["Desenvolver a aplicação","Juciane_Design Thinking Adapter/tasks/desenvolver_a_aplicacao_1049FBC7.html"];
contentPage.processPage.elementUrls["_OtgXEaMwEeuaPL768T4xXQ"] = ["aplicação executando em ambiente de produção","Juciane_Design Thinking Adapter/workproducts/aplicacao_executando_em_ambiente_de_producao_4698C099.html"];
contentPage.processPage.elementUrls["_fUwhYKMpEeuaPL768T4xXQ"] = ["Apresentação do protótipo para o cliente","Juciane_Design Thinking Adapter/tasks/apresentacao_do_prototipo_para_o_cliente_771A0F28.html"];
contentPage.processPage.elementUrls["_M7gN9aMwEeuaPL768T4xXQ"] = ["aplicação funcional","Juciane_Design Thinking Adapter/workproducts/aplicacao_funcional_F915469D.html"];
contentPage.processPage.elementUrls["_XLPYYaMwEeuaPL768T4xXQ"] = ["Ideação","Juciane_Design Thinking Adapter/deliveryprocesses/Ideação_E59F10E.html"];
contentPage.processPage.elementUrls["_fnQUsKMrEeuaPL768T4xXQ"] = ["Definir as tarefas de desenvolvimento","Juciane_Design Thinking Adapter/tasks/definir_as_tarefas_de_desenvolvimento_7AA89A34.html"];
contentPage.processPage.elementUrls["_Hm-EIKMuEeuaPL768T4xXQ"] = ["relatório dos problemas encontrados nos testes","Juciane_Design Thinking Adapter/workproducts/relatorio_dos_problemas_encontrados_nos_testes_791E870B.html"];
contentPage.processPage.elementUrls["_dkQ0I6MpEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_DjgHVaMxEeuaPL768T4xXQ"] = ["relatório dos problemas encontrados nos testes","Juciane_Design Thinking Adapter/workproducts/relatorio_dos_problemas_encontrados_nos_testes_791E870B.html"];
contentPage.processPage.elementUrls["_tpGsl6MwEeuaPL768T4xXQ"] = ["Descrição do cliente sobre o problema","Juciane_Design Thinking Adapter/workproducts/descricao_do_cliente_sobre_o_problema_B785C4CF.html"];
contentPage.processPage.elementUrls["_ZIWlUKMwEeuaPL768T4xXQ"] = ["Prototipação","Juciane_Design Thinking Adapter/deliveryprocesses/Prototipação_8DCC0723.html"];
contentPage.processPage.elementUrls["_DjgHUKMxEeuaPL768T4xXQ"] = ["Realizar testes na aplicação","Juciane_Design Thinking Adapter/tasks/realizar_testes_na_aplicacao_1C3BDEC4.html"];
contentPage.processPage.elementUrls["_imRPFKMhEeuaPL768T4xXQ"] = ["atendimento ao cliente","Juciane_Design Thinking Adapter/roles/atendimento_ao_cliente_E50741EE.html"];
contentPage.processPage.elementUrls["_yaQHYKMwEeuaPL768T4xXQ"] = ["brainstorm","Juciane_Design Thinking Adapter/tasks/brainstorm_9CD1B2BB.html"];
contentPage.processPage.elementUrls["_yaQHYaMwEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_l9FZ4KMhEeuaPL768T4xXQ"] = ["Coletar informações sobre o cliente","Juciane_Design Thinking Adapter/tasks/coletar_informacoes_sobre_o_cliente_D5180351.html"];
contentPage.processPage.elementUrls["_Hm8O8KMuEeuaPL768T4xXQ"] = ["Realizar testes na aplicação","Juciane_Design Thinking Adapter/tasks/realizar_testes_na_aplicacao_1C3BDEC4.html"];
contentPage.processPage.elementUrls["_u1x7EaMwEeuaPL768T4xXQ"] = ["relatório sobre o cliente","Juciane_Design Thinking Adapter/workproducts/relatorio_sobre_o_cliente_C02A708B.html"];
contentPage.processPage.elementUrls["_e2a7YaMwEeuaPL768T4xXQ"] = ["Deploy","Juciane_Design Thinking Adapter/deliveryprocesses/Deploy_ACB9BCB4.html"];
contentPage.processPage.elementUrls["_4TlSQaMwEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_-SF4F6MwEeuaPL768T4xXQ"] = ["protótipo da aplicação","Juciane_Design Thinking Adapter/workproducts/prototipo_da_aplicacao_3F3EB527.html"];
contentPage.processPage.elementUrls["_GaRgIaMxEeuaPL768T4xXQ"] = ["profissional de devops","Juciane_Design Thinking Adapter/roles/profissional_de_devops_1D4ED559.html"];
contentPage.processPage.elementUrls["_Poui06MoEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_2Lb6B6MwEeuaPL768T4xXQ"] = ["feedbacks sobre o prototipo","Juciane_Design Thinking Adapter/workproducts/feedbacks_sobre_o_prototipo_166A0931.html"];
contentPage.processPage.elementUrls["_fUwhZ6MpEeuaPL768T4xXQ"] = ["feedbacks sobre o prototipo","Juciane_Design Thinking Adapter/workproducts/feedbacks_sobre_o_prototipo_166A0931.html"];
contentPage.processPage.elementUrls["_Poui0KMoEeuaPL768T4xXQ"] = ["brainstorm","Juciane_Design Thinking Adapter/tasks/brainstorm_9CD1B2BB.html"];
contentPage.processPage.elementUrls["_2Lb6BaMwEeuaPL768T4xXQ"] = ["atendimento ao cliente","Juciane_Design Thinking Adapter/roles/atendimento_ao_cliente_E50741EE.html"];
contentPage.processPage.elementUrls["_imRPGKMhEeuaPL768T4xXQ"] = ["relatório da análise do problema","Juciane_Design Thinking Adapter/workproducts/relatorio_da_analise_do_problema_5A197C2D.html"];
contentPage.processPage.elementUrls["_GaRgJaMxEeuaPL768T4xXQ"] = ["aplicação funcional","Juciane_Design Thinking Adapter/workproducts/aplicacao_funcional_F915469D.html"];
contentPage.processPage.elementUrls["_9FHMwaMeEeuaPL768T4xXQ"] = ["Desenvolvimento","Juciane_Design Thinking Adapter/capabilitypatterns/Desenvolvimento_4F3255D3.html"];
contentPage.processPage.elementUrls["__wuecaMeEeuaPL768T4xXQ"] = ["Deploy","Juciane_Design Thinking Adapter/capabilitypatterns/Deploy_5459357D.html"];
contentPage.processPage.elementUrls["_wIECUaMwEeuaPL768T4xXQ"] = ["relatório sobre potenciais concorrentes","Juciane_Design Thinking Adapter/workproducts/relatorio_sobre_potenciais_concorrentes_5F207077.html"];
contentPage.processPage.elementUrls["_Hm9dEqMuEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_yaQHY6MwEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_RUzQ0KMtEeuaPL768T4xXQ"] = ["Configurar ambiente de teste","Juciane_Design Thinking Adapter/tasks/configurar_ambiente_de_teste_46D16D6A.html"];
contentPage.processPage.elementUrls["_POcoVKMtEeuaPL768T4xXQ"] = ["aplicação funcional","Juciane_Design Thinking Adapter/workproducts/aplicacao_funcional_F915469D.html"];
contentPage.processPage.elementUrls["_AWRWV6MxEeuaPL768T4xXQ"] = ["ambiente de testes configurado","Juciane_Design Thinking Adapter/workproducts/ambiente_de_testes_configurado_F6C42C7D.html"];
contentPage.processPage.elementUrls["_POS3U6MtEeuaPL768T4xXQ"] = ["definição das tarefas de desenvolvimento","Juciane_Design Thinking Adapter/workproducts/definicao_das_tarefas_de_desenvolvimento_71469337.html"];
contentPage.processPage.elementUrls["_4TucMqMwEeuaPL768T4xXQ"] = ["protótipo da aplicação","Juciane_Design Thinking Adapter/workproducts/prototipo_da_aplicacao_3F3EB527.html"];
contentPage.processPage.elementUrls["_GaRgIKMxEeuaPL768T4xXQ"] = ["Configurar o ambiente de produção","Juciane_Design Thinking Adapter/tasks/configurar_o_ambiente_de_producao_8F531151.html"];
contentPage.processPage.elementUrls["_Poui0aMoEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_0xeddaMwEeuaPL768T4xXQ"] = ["protótipo da aplicação","Juciane_Design Thinking Adapter/workproducts/prototipo_da_aplicacao_3F3EB527.html"];
contentPage.processPage.elementUrls["_AWRWUKMxEeuaPL768T4xXQ"] = ["Configurar ambiente de teste","Juciane_Design Thinking Adapter/tasks/configurar_ambiente_de_teste_46D16D6A.html"];
contentPage.processPage.elementUrls["_JHO1oKMxEeuaPL768T4xXQ"] = ["colocar aplicação em produção","Juciane_Design Thinking Adapter/tasks/colocar_aplicacao_em_producao_802DF2D1.html"];
contentPage.processPage.elementUrls["_POcoUKMtEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_-SF4GaMwEeuaPL768T4xXQ"] = ["aplicação funcional","Juciane_Design Thinking Adapter/workproducts/aplicacao_funcional_F915469D.html"];
contentPage.processPage.elementUrls["_RUzQ0aMtEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_2Lb6AaMwEeuaPL768T4xXQ"] = ["Cliente","Juciane_Design Thinking Adapter/roles/cliente_B8D3AF02.html"];
contentPage.processPage.elementUrls["_6EcREaMeEeuaPL768T4xXQ"] = ["Prototipação","Juciane_Design Thinking Adapter/capabilitypatterns/Prototipação_BCEF8B31.html"];
contentPage.processPage.elementUrls["_-0m0caMeEeuaPL768T4xXQ"] = ["Testes","Juciane_Design Thinking Adapter/capabilitypatterns/Testes_BE79BBBB.html"];
contentPage.processPage.elementUrls["_M7gN8aMwEeuaPL768T4xXQ"] = ["profissional de devops","Juciane_Design Thinking Adapter/roles/profissional_de_devops_1D4ED559.html"];
contentPage.processPage.elementUrls["_fnQUs6MrEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_fUwhZaMpEeuaPL768T4xXQ"] = ["atendimento ao cliente","Juciane_Design Thinking Adapter/roles/atendimento_ao_cliente_E50741EE.html"];
contentPage.processPage.elementUrls["_h8CawKMrEeuaPL768T4xXQ"] = ["Atribuir as tarefas de desenvolvimento","Juciane_Design Thinking Adapter/tasks/atribuir_as_tarefas_de_desenvolvimento_19614B91.html"];
contentPage.processPage.elementUrls["_nWljcaMhEeuaPL768T4xXQ"] = ["relatório sobre potenciais concorrentes","Juciane_Design Thinking Adapter/workproducts/relatorio_sobre_potenciais_concorrentes_5F207077.html"];
contentPage.processPage.elementUrls["_RUzQ16MtEeuaPL768T4xXQ"] = ["ambiente de testes configurado","Juciane_Design Thinking Adapter/workproducts/ambiente_de_testes_configurado_F6C42C7D.html"];
contentPage.processPage.elementUrls["_CDma0KMxEeuaPL768T4xXQ"] = ["Preparar aplicação para testes","Juciane_Design Thinking Adapter/tasks/preparar_aplicacao_para_testes_A8173545.html"];
contentPage.processPage.elementUrls["_fnQUt6MrEeuaPL768T4xXQ"] = ["definição das tarefas de desenvolvimento","Juciane_Design Thinking Adapter/workproducts/definicao_das_tarefas_de_desenvolvimento_71469337.html"];
contentPage.processPage.elementUrls["_GaRgI6MxEeuaPL768T4xXQ"] = ["equipe de desenvolvimento","Juciane_Design Thinking Adapter/roles/equipe_de_desenvolvimento_360DFBF1.html"];
contentPage.processPage.elementUrls["_imRPEqMhEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_tpGsmaMwEeuaPL768T4xXQ"] = ["relatório da análise do problema","Juciane_Design Thinking Adapter/workproducts/relatorio_da_analise_do_problema_5A197C2D.html"];
contentPage.processPage.elementUrls["_dkQ0IaMpEeuaPL768T4xXQ"] = ["designer","Juciane_Design Thinking Adapter/roles/designer_78C0B9A6.html"];
contentPage.processPage.elementUrls["_d_UUQaMwEeuaPL768T4xXQ"] = ["Testes","Juciane_Design Thinking Adapter/deliveryprocesses/Testes_76E980F4.html"];
contentPage.processPage.elementUrls["_DjgHU6MxEeuaPL768T4xXQ"] = ["gestor de projetos","Juciane_Design Thinking Adapter/roles/gestor_de_projetos_B4B3CF55.html"];
contentPage.processPage.elementUrls["_tpGskaMwEeuaPL768T4xXQ"] = ["Cliente","Juciane_Design Thinking Adapter/roles/cliente_B8D3AF02.html"];
contentPage.processPage.elementUrls["_nWljcKMhEeuaPL768T4xXQ"] = ["Analisar os potenciais competidores","Juciane_Design Thinking Adapter/tasks/analisar_os_potenciais_competidores_462BB05A.html"];
contentPage.processPage.elementUrls["_DjgHUaMxEeuaPL768T4xXQ"] = ["Cliente","Juciane_Design Thinking Adapter/roles/cliente_B8D3AF02.html"];
contentPage.processPage.elementUrls["_M7gN96MwEeuaPL768T4xXQ"] = ["ambiente de produção configurado","Juciane_Design Thinking Adapter/workproducts/ambiente_de_producao_configurado_273D6861.html"];
contentPage.processPage.elementUrls["_imRPEKMhEeuaPL768T4xXQ"] = ["Cliente","Juciane_Design Thinking Adapter/roles/cliente_B8D3AF02.html"];
contentPage.processPage.elementUrls["_Hm9dEKMuEeuaPL768T4xXQ"] = ["Cliente","Juciane_Design Thinking Adapter/roles/cliente_B8D3AF02.html"];
contentPage.processPage.elementUrls["_bmT1gaMwEeuaPL768T4xXQ"] = ["Análise","Juciane_Design Thinking Adapter/deliveryprocesses/Análise_2B2D51EB.html"];
contentPage.processPage.elementUrls["_fnQUtaMrEeuaPL768T4xXQ"] = ["protótipo da aplicação","Juciane_Design Thinking Adapter/workproducts/prototipo_da_aplicacao_3F3EB527.html"];
contentPage.processPage.elementUrls["_4TucMKMwEeuaPL768T4xXQ"] = ["documento com escopo da aplicação a ser desenvolvida","Juciane_Design Thinking Adapter/workproducts/documento_com_escopo_da_aplicacao_a_ser_desenvolvida_F3499D72.html"];
contentPage.processPage.elementUrls["_yrOn0aMeEeuaPL768T4xXQ"] = ["Imersão","Juciane_Design Thinking Adapter/capabilitypatterns/Análise_6ED8EFA0.html"];
contentPage.processPage.elementUrls["_dkQ0IKMpEeuaPL768T4xXQ"] = ["desenvolver um protótipo da aplicação","Juciane_Design Thinking Adapter/tasks/desenvolver_um_prototipo_da_aplicacao_A0BA7727.html"];
contentPage.processPage.elementUrls["_tpGskKMwEeuaPL768T4xXQ"] = ["Analisar o problema","Juciane_Design Thinking Adapter/tasks/analisar_o_problema_20968CD5.html"];
contentPage.processPage.elementUrls["_c1wEIaMwEeuaPL768T4xXQ"] = ["Desenvolvimento","Juciane_Design Thinking Adapter/deliveryprocesses/Desenvolvimento_7130F4BD.html"];
contentPage.processPage.elementUrls["_POcoUqMtEeuaPL768T4xXQ"] = ["protótipo da aplicação","Juciane_Design Thinking Adapter/workproducts/prototipo_da_aplicacao_3F3EB527.html"];
contentPage.processPage.elementUrls["_POS3UKMtEeuaPL768T4xXQ"] = ["Desenvolver a aplicação","Juciane_Design Thinking Adapter/tasks/desenvolver_a_aplicacao_1049FBC7.html"];
contentPage.processPage.elementUrls["_8FbzQKMwEeuaPL768T4xXQ"] = ["Atribuir as tarefas de desenvolvimento","Juciane_Design Thinking Adapter/tasks/atribuir_as_tarefas_de_desenvolvimento_19614B91.html"];
contentPage.processPage.elementUrls["_SvBzIaMtEeuaPL768T4xXQ"] = ["aplicação preparada para testes","Juciane_Design Thinking Adapter/workproducts/aplicacao_preparada_para_testes_8DC6236D.html"];
